# Generated by Django 5.2.4 on 2025-07-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("INVESTIGATING", "Investigating"),
                    ("RESOLVED", "Resolved"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
